apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: appmesh-prometheus
  namespace: appmesh-system
spec:
  releaseName: appmesh-prometheus
  chart:
    repository: https://aws.github.io/eks-charts
    name: appmesh-prometheus
    version:  0.3.0
  values:
    retention: 2h
